[profile.default]
src = "src/contracts"
out = "out"
libs = ["lib"]
remappings = [
    "lib/openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

optimizer = true
optimizer_runs = 200
via_ir = false

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[doc]
out = "docs"

[rpc_endpoints]
avalanche = "http://127.0.0.1:41773/ext/bc/wtHFpLKd93iiPmBBsCdeTEPz6Quj9MoCL8NpuxoFXHtvTVeT1/rpc"
chaosstarnetwork = "http://127.0.0.1:41773/ext/bc/wtHFpLKd93iiPmBBsCdeTEPz6Quj9MoCL8NpuxoFXHtvTVeT1/rpc"

# [etherscan]
# avalanche = { api_url = "http://127.0.0.1:9650/ext/bc/ChaosStarNetwork/rpc", api_key = "" }

